export const MenuHeadings = [
  {
    name: 'String',
    content: [
      { item: 'Bin String', href: '#' },
      { item: 'Hex String', href: '#' },
      { item: 'HTML Escape', href: '#' },
      { item: 'Base32', href: '#' },
      { item: 'Base45', href: '#' },
      { item: 'Base64', href: '#' },
      { item: 'Ascii85', href: '#' },
      { item: 'Quoted-printable', href: '#' },
      { item: 'Program String', href: '#' },
      { item: 'Unicode Escape', href: '#' },
      { item: 'Morse Code', href: '#' },
      { item: 'Naming Convos', href: '#' },
      { item: 'Line Sort', href: '#' },
      { item: 'Line Unique', href: '#' },
      { item: 'Text Reverse', href: '#' },
      { item: 'Letter Case', href: '#' },
      { item: 'Text Initials', href: '#' },
      { item: 'Character Width', href: '#' },
      { item: 'Unicode Normalization', href: '#' },
    ],
  },
  {
    name: 'Number',
    content: [
      { item: 'Roman Numerals', href: '#' },
      { item: 'English Numerals', href: '#' },
      { item: 'Octal Numbers', href: '#' },
      { item: 'Binary Numbers', href: '#' },
      { item: 'Hexadecimal Numbers', href: '#' },
    ],
  },
  {
    name: 'Date',
    content: [
      { item: 'UNIX Times', href: '#' },
      { item: 'W3C-DTF', href: '#' },
      { item: 'ctime', href: '#' },
      { item: 'ISO8601', href: '#' },
      { item: 'RFC2822', href: '#' },
    ],
  },
  {
    name: 'Color',
    content: [
      { item: 'Color Name', href: '#' },
      { item: 'RGB Colors', href: '#' },
      { item: 'HSV Colors', href: '#' },
      { item: 'HSL Colors', href: '#' },
      { item: 'LCH Colors', href: '#' },
      { item: 'OKLCH Colors', href: '#' },
    ],
  },
  {
    name: 'Cipher',
    content: [
      { item: 'Caesar', href: '#' },
      { item: 'ROT13', href: '#' },
      { item: 'ROT18', href: '#' },
      { item: 'ROT47', href: '#' },
      { item: 'Atbash', href: '#' },
      { item: 'Affine', href: '#' },
      { item: 'Vigenère', href: '#' },
      { item: 'Enigma', href: '#' },
      { item: 'Scytale', href: '#' },
      { item: 'Rail Fence', href: '#' },
    ],
  },
  {
    name: 'Hash',
    content: [
      { item: 'MD2', href: '#' },
      { item: 'MD5', href: '#' },
      { item: 'SHA1', href: '#' },
      { item: 'SHA256', href: '#' },
      { item: 'SHA384', href: '#' },
      { item: 'SHA512', href: '#' },
    ],
  },
]
